### ISSUE TITLE
Cannot find phpunit.xml anymore

### ISSUE THREAD

**Issue by dp-anto** [recca0120/vscode-phpunit#186] opened 2024-11-04 14:38 UTC
I have the `phpunit.xml` file not in the root directory, but inside a custom subdirectory and the fun fact is that until few weeks ago the extension was able to detect it and list all the tests. However now it doesn't seem to find the `phpunit.xml` file anymore and it gets showing me the following error:

> ENOENT: no such file or directory, open '/home/abcde/my-app/phpunit.xml'

Did something change in the extension or in vscode?

Vscode Version: `1.95.1`
Extension Version: `v3.3.3`

**Comment by ThatsJustCheesy** [comment] 2024-11-04 17:48
I think this is a duplicate of #180. It seems this is due to a recent extension update.

A workaround:

![image](https://github.com/user-attachments/assets/93d5b2b5-3ce3-442f-ad1b-fd570ab91fdb)

**Comment by recca0120** [comment] 2024-11-04 19:44
version 3.3.4 fixed

**Closed by recca0120** 2024-11-04 19:44 UTC

**Comment by dp-anto** [comment] 2024-11-19 11:54
Hi @recca0120 I have again the same exact problem with version 3.4.0

**Comment by dp-anto** [comment] 2024-11-19 14:05
to workaround it I've duplicated the phpunit.xml file in the root (i've also tried with a symbolic link but it doesn't work)
