### ISSUE TITLE
Using docker-compose in phpunit.php does not seem to work.

### ISSUE THREAD

**Issue by Xachman** [recca0120/vscode-phpunit#76] opened 2020-10-10 16:39 UTC
if I add:

``` json
{
    "phpunit.php": "/usr/bin/docker-compose run --rm app php",
    "phpunit.phpunit": "/var/www/html/vendor/bin/phpunit
}
```

Config options and try to run the tests I get back. 

```
spawn /usr/bin/docker-compose run --rm app php ENOENT
```

**Comment by Xachman** [comment] 2020-10-12 19:41
This issue is because on my system it needs to be a file.  I made a docker-phpunit.sh file:

~~~ bash
#!/bin/bash

docker-compose run --rm app /var/www/html/vendor/bin/phpunit $@
~~~

and made changes to the settings.json

~~~ json
{
    "phpunit.phpunit": "/path/to/file/docker-phpunit.sh",
    "phpunit.args": ["--configuration", "/var/www/html/phpunit.xml"],
    "phpunit.relativeFilePath": true
}
~~~

This works in general but now I get the error every once and a while. 

~~~
(node:6089) UnhandledPromiseRejectionWarning: Error: Unhandled method TestRetryEvent-0e1f51777fd53e8d4de77095197d3029
    at /home/user/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9133
    at /home/user/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9427
    at Immediate.<anonymous> (/home/user/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9788)
    at processImmediate (internal/timers.js:439:21)
(node:6089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
~~~

**Comment by Xachman** [comment] 2020-10-12 19:44
https://github.com/recca0120/vscode-phpunit/issues/33 may be related

**Comment by perebusquets** [comment] 2020-10-15 09:32
It's happening for me too, I get this error after running all the tests succesfully, then trying to run the tests again returns the error above.

**Comment by dsclee1** [comment] 2020-11-13 16:43
Just started using this tool. I'm running against a docker-compose container sitting on a Debian box, which I'm connecting to using the inbuilt vscode SSH bridge (Remote-SSH). I'm experiencing the same issues as described.

I've set up my fields a little differently.


```
"phpunit.relativeFilePath": true,
"phpunit.php": "/usr/bin/docker exec my_container php",
"phpunit.phpunit": "/var/www/html/vendor/bin/phpunit",
"phpunit.shell": "/bin/bash",
```


The tests run fine as long as there's no failures, but as soon as there are the module crashes out and can't be recovered without a restart of the SSH connection.

I get the same error message as @Xachman.

```
(node:5145) UnhandledPromiseRejectionWarning: Error: Unhandled method TestRunStartedEvent-0199eba5e9da448952078e8954b366f9
    at /home/me/.vscode-server/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9133
    at /home/me/.vscode-server/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9427
    at Immediate.<anonymous> (/home/me/.vscode-server/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9788)
    at processImmediate (internal/timers.js:439:21)
(node:5145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
```

**Comment by enricodias** [comment] 2021-05-21 20:50
Same problem here. I get a `UnhandledPromiseRejectionWarning` if a test fails and then I need to restart vscode.

**Comment by antichris** [comment] 2021-06-18 11:15
@perebusquets, @enricodias Please don't (ever) just comment "same here" — +1 the issue instead. Only post if you have valuable information to add to the discussion.

Also, you don't *need* to restart vscode, restarting the extension host (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>, "Developer: Restart Extension Host") is enough.

**Comment by enricodias** [comment] 2021-06-18 15:31
@antichris It was intentional to show that this issue is still relevant almost a year after the last reply. Having to restart the extension host is pretty much the same hassle as having to restart vscode itself, at least for me.

**Comment by antichris** [comment] 2021-06-18 16:58
>It was intentional to show that this issue is still relevant almost a year after the last reply
<details><summary>Successful deflection is successful.</summary>

Although I'd speculate, had you thought about it that way at that particular moment, you'd probably written it like "hey, this is still happening, it's very annoying/frustrating, is there a fix coming?" (or something along the lines).

*Also I was surprised at first how you managed to get "almost a year" from November 13 to May 21 (6 months 8 days), but that, although appears to shed light on your tendency to stick to the facts, is not very pertinent to the discussion.*
</details>

What matters is that I do agree — having to restart anything *every single flipping time* a test fails is extremely frustrating and renders this extension practically useless, considering how tests have to be written to fail first, before enough code has been written (or changed) for them to start passing. We need a fix for this.

**Comment by enricodias** [comment] 2021-08-12 17:50
It appears that problem that happens when a test fails seems to be caused by the file paths reported by phpunit, they differ between the container and the host machine. It works when no tests fail because the extension doesn't need to open any file in that case.

As a workaround, I'm using `sed` to replace the paths reported by phpunit with the path used in the host machine:

```bash
#!/bin/bash

docker-compose exec -T DOCKER_IMAGE bin/phpunit ${@:2} | sed "s|\./|HOST_PATH|g"
```

**Comment by Xachman** [comment] 2021-08-13 01:43
@enricodias I can confirm that this will in fact fix the issue.  I had to make some adjustments to your script in my case this worked.

```
#!/bin/bash

docker-compose exec -T DOCKER_IMAGE bin/phpunit $@ | sed "s|/path/in/container|/path/on/host|g"
```

I can finally use this extension again! I appreciate all the time you put into figuring out this issue!

**Comment by recca0120** [comment] 2022-12-06 19:16
try version 3.0

**Closed by recca0120** 2022-12-06 19:16 UTC
