### ISSUE TITLE
[2.0.73] All my tests show *** duplicate ID *** now.

### ISSUE THREAD

**Issue by ellisio** [recca0120/vscode-phpunit#63] opened 2020-06-29 19:18 UTC
As of v2.0.73, all of my tests show `*** duplicate ID ***` in the test explorer UI. When I attempt to run a test, I get "No tests executed!" from phpunit.

Rolling back to v2.0.72 resolves this.

Here is an example test (located in `tests/Feature/PhotosControllerTest.php`):

```
<?php

namespace Tests\Feature;

use App\Photo;
use App\User;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class PhotosControllerTest extends TestCase
{
    public function testListSuccess()
    {
        // Test steps...
    }

    public function testCreateSuccess()
    {
        // Test steps...
    }

    public function testDeleteSuccess()
    {
        // Test steps...
    }
}
```

**Comment by nick322** [comment] 2020-06-30 09:04
I have the same problem.

**Comment by MichaelPanW** [comment] 2020-06-30 09:04
I have the same problem.

**Comment by rmarshall9n** [comment] 2020-06-30 10:55
The troubleshooting section on the marketplace has a workaround:

https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit

I followed the instructions and I can now run all the tests in a class at the same time, however, when I run a single test, I still get "No tests executed!".

**Comment by recca0120** [comment] 2020-06-30 11:56
OK I'll rollback.

**Comment by MichMich** [comment] 2020-06-30 11:58
Just for the record: same here.

**Comment by aphix-mark** [comment] 2020-06-30 12:23
Take a look at the troubleshooting section "_All tests are appearing twice with "*** duplicate ID ***" found._" of the readme.

I think when PR #50 came in, it expanded the default folders it looks in. This has meant for case-insensitive file systems it will try import the same test twice.... Reversing this will mean for case sensitive file systems, their tests may not appear by default..... Both as equally bad..?

In either case the fix is to specify your test folder `"phpunit.files": "{test,tests}/**/*Test.php"` for a lowercase t...

Can you test this out and find out if it works rather than rolling back?

**Comment by MichMich** [comment] 2020-06-30 12:47
It seems my config was:
```
{test,tests,Test,Tests}/**/*Test.php

```

When I changed it to:
```
{test,tests}/**/*Test.php
```

The duplicate tests disappear, but when I run a test, it still says: "No tests executed!"

**Comment by nick322** [comment] 2020-07-01 09:49
@aphix-mark 
When it update to [2.0.74] , my config auto changed to '{test,tests,Test,Tests}/**/*Test.php'.
Then I changed it to '{test,tests}/**/*Test.php'. It's OK.

**Comment by nick322** [comment] 2020-07-01 10:10
> It seems my config was:
> 
> ```
> {test,tests,Test,Tests}/**/*Test.php
> ```
> 
> When I changed it to:
> 
> ```
> {test,tests}/**/*Test.php
> ```
> 
> The duplicate tests disappear, but when I run a test, it still says: "No tests executed!"

try to restart VScode.

**Comment by MichMich** [comment] 2020-07-01 11:15
Same here. If I run all tests, it's ok. But if I run a specific test it is still nog working.

**Comment by MichMich** [comment] 2020-07-07 13:04
Any progress on this? Would be great if we could use the plugin again.

**Comment by MrMage** [comment] 2020-07-07 15:12
+1 — I also had duplicate tests globally (fixed by changing the glob pattern), but running an individual test does not work at all.

**Comment by ellisio** [comment] 2020-07-07 22:47
@MichMich You can. Downgrade to v2.0.72.

![image](https://user-images.githubusercontent.com/127468/86852165-7da4a100-c071-11ea-891c-5b1df38b7e00.png)

**Comment by MichMich** [comment] 2020-07-08 14:42
@ellisio Thanks! That worked.

**Comment by aphix-mark** [comment] 2020-07-09 14:43
Thanks all for the feedback above.

The title of the issue is to do with the *** duplicate ID *** issue - which is sorted by amending your config `"phpunit.files": "{test,tests}/**/*Test.php"` when you have a case insensitive filesystem.

The next issue, is to do with tests not executing - not related to this one but on #64 there is some really good detail about the issue, so I'm closing this solved issue and for anyone with the "no test executed" issue, please follow #64

**Closed by aphix-mark** 2020-07-09 14:43 UTC

**Comment by Chrismas-tech** [comment] 2022-02-22 12:22
I had the same problem, I just changed the version to the 2.0.72 and everything worked :)

Hope it helps someone
